name: Commit Check

on:
  push:
    branches:
      - main
      - dev

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Run ESLint for linting
      - name: Run ESLint
        run: npm run lint

      # Step 6: Run Prettier check
      - name: Prettier Check
        run: npm run format:check

      # Step 7: Run tests
      - name: Run tests
        run: npm run test

      # Step 10: Build the project
      - name: Build the project
        run: npm run build
